### PR TITLE
feat: add default terminal type

### PR DESCRIPTION
**Pull request by bozkayasalihx**
* add a startup configuration that sets the default terminal type

### CODE REVIEW

**Comment by siduck** [comment]
@bozkayasalihx  nvterm is soon being un-maintained :v

**Comment by bozkayasalihx** [comment]
why?  its working so good
do you have an suggestion for the replacement then?

**Comment by siduck** [comment]
@bozkayasalihx I didnt write the codebase of nvterm, i feel its messy and tons of issues too. So i re-wrote mine for NvChad

https://github.com/NvChad/ui/blob/v3.0/lua/nvchad/term/init.lua 

Needs v3.0 of nvchad to use ( v3.0 is beta ) . Also in nvterm, you can only toggle 1 float/horizontal/vertical term, but in my term module you can toggle unlimited of them!! 

it also provides a "cmd" option for non toggleable terms, and hl option if you want to change bg color of the terminal

**Comment by bozkayasalihx** [comment]
i haven't encountered any (kinda) of the bugs you mentioned, but it's good to hear that you've been working on a less buggy version. Will this improved version be offered as a separate plugin or directly integrated into nvchad?

**Comment by siduck** [comment]
i'm not talking about bugs, in nvterm you could only toggle 1 float/vert/horiz windows so 3 windows in total, but in this new module you can toggle how many ever you want, just need to provide an unique ID to each function.

Also you can use all of the nvchad ui/base46 stuff without nvchad. Just make a module `(core.utils).load_config()` which returns the default table in NvChad. This term module only depends on that config table

**Pull request closed without merging**
